### ISSUE TITLE
Umlauts in URL

### ISSUE THREAD

**Issue by DFranzen** [m0ngr31/kodi-music-proxy#1]
If the URL to be forwarded to contains an Umlaut, the proxy responds with "File not found". 
I have verified that the file exists via http without the proxy.

**Comment by m0ngr31** [comment]
Can you give me an example of the URL? And the character in question?

**Comment by DFranzen** [comment]
I send you an email with a few links. Since they contain my Kodi address including user and password, I didn't think sharing them publicly is a good idea

**Comment by m0ngr31** [comment]
Your PR is merged, so this should be good now.
